version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ft_transcendence_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ft_user
      POSTGRES_PASSWORD: ft_password
      POSTGRES_DB: ft_transcendence
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: