version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ft_transcendence_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ft_user
      POSTGRES_PASSWORD: ft_password
      POSTGRES_DB: ft_transcendence
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./game_service
    container_name: ft_transcendence_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://ft_user:ft_password@postgres:5432/ft_transcendence
      PORT: "3000"
    depends_on:
      - postgres

volumes:
  pgdata: