services:
  db:
    image: postgres:15
    container_name: chat_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_service
    ports:
      - "5432:5432"
    networks:
      - app-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: mait-taj@gmail.com   # your login email
  #     PGADMIN_DEFAULT_PASSWORD: 1234            # your login password
  #   ports:
  #     - "5050:80"    # access pgAdmin at http://localhost:5050
  #   depends_on:
  #     - db
  #   networks:
  #     - app-net

  app:
    build: ./backend
    container_name: chat_app
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/chat_service
    volumes:
      - ./backend:/app
    networks:
      - app-net
    ports:
      - "3000:3000"
    # command: npm run dev

volumes:
  postgres_data:
networks:
  app-net:
    driver: bridge