services:
  db:
    image: postgres:16
    restart: always
    container_name : db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sayf
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - app-network
    restart: always
    ports:
      - "1234:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: hh@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    depends_on:
      - db

  auth:
    container_name: auth
    build: ../backend/auth
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    networks:
      - app-network
    volumes:
      - ../backend/auth/myauth:/app
      - vault-secrets:/vault/secrets
    depends_on:
     - db
     - vault
     - vault-agent
    
  frontend:
    container_name: frontend
    restart: always
    networks:
      - app-network
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=pk_test_...
      - VITE_API_URL=http://localhost:8080/
      - VITE_CHAT_API=https://localhost:8443/api
    build: ../frontend
    volumes:
      - ../frontend:/app/
      - /app/node_modules 

  nginx:
    build : ./nginx
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - app-network
    restart: always
    depends_on:
      - frontend
      - auth
      - db
      - game-api
      - chat-api
      - chat-system

  game:
    build: ../backend/game_service
    container_name: game
    restart: unless-stopped
    networks:
      - app-network
    environment:
      DATABASE_URL: postgres://sayf:1234@db:5432/mydb
      SECRET_KEY: ${DJANGO_SECRET_KEY}
    ports:
      - "1339:3000"
    depends_on:
      - db
      - auth
      - frontend
  
  game-api:
    build: ../backend/ai_service/services/game_api
    container_name: game-api
    ports:
      - "5001:5001"
    networks:
      - app-network

  chat-api:
    build: ../backend/ai_service/services/chat_api
    container_name: chat-api
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy    
      game-api:
        condition: service_started
    env_file:
      - .env
    environment:
      GAME_API_URL: http://game-api:5001
    volumes:
      - ../backend/ai_service/static:/app/static
      - ../backend/ai_service/templates:/app/templates
      - ../backend/ai_service/uploads:/app/uploads
    networks:
      - app-network

  chat-system:
    build:
        context: ../backend/chat/backend
        dockerfile: Dockerfile
    container_name: chat-system
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY: 'django-insecure-4vkpyy2bkd3(%hi=nhqdr(yx5j71%*zf!o!ej2kfnivhbno!%n'
      DATABASE_URL: postgres://sayf:1234@db:5432/mydb
    volumes:
      - ../backend/chat/backend:/app
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: game-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pp_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s   
      timeout: 5s      
      retries: 10       

  cert-init:
    image: alpine/openssl
    container_name: cert-init
    volumes:
      - ./vault/userconfig/tls:/vault/userconfig/tls
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        set -e

        if [ -f /vault/userconfig/tls/vault.crt ]; then
          echo "Certs already exist, skipping..."
          exit 0
        fi

        cd /vault/userconfig/tls

        openssl genrsa -out ca.key 4096
        openssl req -new -x509 -days 3650 -key ca.key -out ca.crt \
          -subj "/CN=vault-ca/O=MyOrg"

        openssl genrsa -out vault.key 2048
        openssl req -new -key vault.key -out vault.csr \
          -subj "/CN=vault/O=MyOrg"

        cat > san.cnf << 'EOF'
        [req]
        req_extensions = v3_req
        distinguished_name = req_distinguished_name
        [req_distinguished_name]
        [v3_req]
        basicConstraints = CA:FALSE
        keyUsage = digitalSignature, keyEncipherment
        extendedKeyUsage = serverAuth, clientAuth
        subjectAltName = @alt_names
        [alt_names]
        DNS.1 = vault
        DNS.2 = localhost
        DNS.3 = vault.test.lan
        IP.1  = 127.0.0.1
        EOF

        openssl x509 -req -days 365 \
          -in vault.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
          -out vault.crt \
          -extfile san.cnf -extensions v3_req

        chmod 640 vault.key
        chown -R 100:100 /vault/userconfig/tls
    
  vault:
    privileged: true
    build: ./vault/
    restart : always
    container_name: vault
    depends_on:
      cert-init:
        condition: service_completed_successfully
    ports:
    - "8201:8201"
    - "8200:8200"
    environment:
      VAULT_API_ADDR: "https://vault:8200"
      VAULT_ADDR : "https://127.0.0.1:8200"
      VAULT_CACERT: ./vault/userconfig/tls/ca.crt
    cap_add:
    - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/userconfig:/vault/userconfig
      - ./vault/data:/vault/data
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    networks:
      - app-network

  vault-agent:
    privileged: true
    build : ./agent/
    user : root
    cap_add:
      - IPC_LOCK
    container_name: vault-agent
    restart: always
    volumes:
      - ./agent/vault-agent-config.hcl:/vault/config/agent.hcl:ro
      - ./templates:/vault/templates
      - vault-secrets:/vault/secrets
      - ./vault/userconfig/tls/ca.crt:/vault/certs/ca.crt
      - ./vault/userconfig/:/vault/userconfig/   
    networks:
      - app-network
    depends_on:
      - vault

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  pp_data:
  vault-secrets:
  approle-creds: