server {
    listen 80;
<<<<<<< HEAD
    client_max_body_size 20M; 
    
    location ~* \.(txt|log|config)$ { 
        deny all; 
    }
    
    location ~ /\.env$ {
        deny all;
        access_log off;
        log_not_found off;
    }
=======
    client_max_body_size 50M; 
>>>>>>> 358aa23 (SA)

    # all endpoints : example : http://localhost:8080/authent/login will redirect to 
    # http://auth:8000/login


    # Frontend endpoint :
    location / {
        proxy_pass http://frontend:5173/;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /authent/ {
        proxy_pass http://auth:8000/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
<<<<<<< HEAD
        location /game_br/ {
        proxy_pass http://game-api:5001/api/ai-move;
=======

    # Login endpoint :
    location /authent/login {
        proxy_pass http://auth:8000/login/;
>>>>>>> 2d98fb0 (SA)
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

<<<<<<< HEAD
    location /chatbot/ {
        proxy_pass http://chat-api:5000/api/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
        location /static/ {
        proxy_pass http://chat-api:5000/static/;
=======

    # Register endpoint :
    location /authent/register {
        proxy_pass http://auth:8000/register/;
>>>>>>> 2d98fb0 (SA)
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

<<<<<<< HEAD
    location /api/ {
        proxy_pass http://chat-system:3000/api/;
=======

    # logout endpoint :
    location /authent/logout
    {
        proxy_pass http://auth:8000/logout/;
>>>>>>> 2d98fb0 (SA)
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
<<<<<<< HEAD
}
=======


    # endpoint for checking the token from cookies :
    location /authent/protected
    {
        proxy_pass http://auth:8000/protected/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;       
    }

    
    location /authent/users
    {
        proxy_pass http://auth:8000/users/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;       
    }
    # location /static/ {
    #     alias /app/static/; 
    # }
<<<<<<< HEAD
}
>>>>>>> 2d98fb0 (SA)
=======
}
>>>>>>> 358aa23 (SA)
