# Generated by Django 5.2.12 on 2026-03-15 04:01

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(db_column='creatorId', on_delete=django.db.models.deletion.CASCADE, related_name='createdTournaments', to='authentication.user')),
                ('winner', models.ForeignKey(blank=True, db_column='winnerId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wonTournaments', to='authentication.user')),
            ],
            options={
                'db_table': 'Tournament',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=9)),
                ('status', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(blank=True, db_column='tournamentId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='authentication.tournament')),
                ('playerO', models.ForeignKey(db_column='playerOId', on_delete=django.db.models.deletion.CASCADE, related_name='gamesAsPlayerO', to='authentication.user')),
                ('playerX', models.ForeignKey(db_column='playerXId', on_delete=django.db.models.deletion.CASCADE, related_name='gamesAsPlayerX', to='authentication.user')),
                ('winner', models.ForeignKey(blank=True, db_column='winnerId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wonGames', to='authentication.user')),
            ],
            options={
                'db_table': 'Game',
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('seed', models.IntegerField()),
                ('eliminated', models.BooleanField(default=False)),
                ('eliminatedInRound', models.IntegerField(blank=True, null=True)),
                ('tournament', models.ForeignKey(db_column='tournamentId', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='authentication.tournament')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='tournamentEntries', to='authentication.user')),
            ],
            options={
                'db_table': 'TournamentParticipant',
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
