# Generated by Django 5.2.13 on 2026-05-02 09:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Conversation',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, default='/authent/media/images/pipi.jpg', null=True, upload_to='images/')),
                ('status', models.CharField(default='Online', max_length=50)),
                ('user_status', models.CharField(default='Offline', max_length=50)),
                ('role', models.CharField(default='user', max_length=50)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(db_column='creatorId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournaments_created', to='authentication.user')),
                ('winner', models.ForeignKey(blank=True, db_column='winnerId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournaments_won', to='authentication.user')),
            ],
            options={
                'db_table': 'Tournament',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(db_column='conversationId', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='authentication.conversation')),
                ('sender', models.ForeignKey(db_column='senderId', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='authentication.user')),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), size=9)),
                ('status', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(blank=True, db_column='tournamentId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='authentication.tournament')),
                ('player_o', models.ForeignKey(db_column='playerOId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_as_o', to='authentication.user')),
                ('player_x', models.ForeignKey(db_column='playerXId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_as_x', to='authentication.user')),
                ('winner', models.ForeignKey(blank=True, db_column='winnerId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_won', to='authentication.user')),
            ],
            options={
                'db_table': 'Game',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(db_column='receiverId', on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='authentication.user')),
                ('requester', models.ForeignKey(db_column='requesterId', on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='authentication.user')),
            ],
            options={
                'db_table': 'Friend',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='user1',
            field=models.ForeignKey(db_column='user1Id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user1', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2',
            field=models.ForeignKey(db_column='user2Id', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user2', to='authentication.user'),
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('seed', models.IntegerField()),
                ('eliminated', models.BooleanField(default=False)),
                ('eliminated_in_round', models.IntegerField(blank=True, null=True)),
                ('tournament', models.ForeignKey(db_column='tournamentId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to='authentication.tournament')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournament_entries', to='authentication.user')),
            ],
            options={
                'db_table': 'TournamentParticipant',
                'indexes': [models.Index(fields=['tournament'], name='TournamentP_tournam_78ba51_idx'), models.Index(fields=['user'], name='TournamentP_userId_5051bc_idx')],
                'unique_together': {('tournament', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['creator'], name='Tournament_creator_7146f9_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['winner'], name='Tournament_winnerI_596780_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='Message_senderI_66e146_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation'], name='Message_convers_994cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='Message_created_c0d018_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player_x'], name='Game_playerX_97fec7_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player_o'], name='Game_playerO_b08a59_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['winner'], name='Game_winnerI_f698b6_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['tournament'], name='Game_tournam_9d2960_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['requester'], name='Friend_request_a4313e_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['receiver'], name='Friend_receive_de7d64_idx'),
        ),
        migrations.AddIndex(
            model_name='friend',
            index=models.Index(fields=['status'], name='Friend_status_b351a2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user1'], name='Conversatio_user1Id_7db341_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user2'], name='Conversatio_user2Id_2e1cca_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='Conversatio_created_ff7d50_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='Conversatio_updated_6cc367_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('user1', 'user2')},
        ),
    ]
