# Generated by Django 5.2.11 on 2026-02-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='password',
            field=models.CharField(default='tmp123', max_length=255),
            preserve_default=False,
        ),
    ]
