# Generated by Django 5.2.12 on 2026-03-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('user', 'User'), ('guest', 'Guest')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
