# Generated by Django 5.2.14 on 2026-05-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/pipi.jpg', null=True, upload_to='images/'),
        ),
    ]
