# Generated by Django 5.2.13 on 2026-04-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/authent/media/images/pipi.jpg', null=True, upload_to='images/'),
        ),
    ]
